PhoneContacts/Models/ErrorViewModel.cs
using System;

namespace PhoneContacts.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PhoneContacts/Controllers/AddController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntitiyFramework;
using EntitiyLayer.Concrete;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PhoneContacts.Controllers
{
    public class AddController : Controller
    {
        UserManager userManager = new UserManager(new EfUserDal());
        [HttpGet]
        public PartialViewResult AddUser()
        {
            return PartialView();
        }

        [HttpPost]
        public IActionResult AddUser(User u)
        {
            userManager.TAdd(u);
            return View();
        }
    }
}

PhoneContacts/Controllers/DeleteController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntitiyFramework;
using EntitiyLayer.Concrete;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PhoneContacts.Controllers
{
    public class DeleteController : Controller
    {
        UserManager userManager = new UserManager(new EfUserDal());

        [HttpGet]
        public PartialViewResult Index()
        {
            return PartialView();
        }

        [HttpPost]
        public IActionResult Index(User u)
        { 
            userManager.TDelete(u);
            return RedirectToAction("Read","Index");
        }

    }
}

PhoneContacts/Controllers/HomeController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntitiyFramework;
using EntitiyLayer.Concrete;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PhoneContacts.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace PhoneContacts.Controllers
{
    public class HomeController : Controller
    {
         
      
        public IActionResult Index()
        {
             
            return View();
        } 
         
    }
}

PhoneContacts/Controllers/ReadController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntitiyFramework;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PhoneContacts.Controllers
{
    public class ReadController : Controller
    {
        UserManager userManager = new UserManager(new EfUserDal());
        public IActionResult Index()
        {
            var values = userManager.TGetList();
            return View(values);
        }
    }
}

PhoneContacts/Views/Add/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

<div>
    <form method="post">
        <input type="text" class="form-control" name="firstName" placeholder="Adınız" /> <br />
        <input type="text" class="form-control" name="lastName" placeholder="Soyadınız" /> <br />
        <input type="text" class="form-control" name="company" placeholder="Çalıştığınız Şirket" /> <br />
        <input type="text" class="form-control" name="phoneNumber" placeholder="Telefon Numarası" /> <br />
        <input type="text" class="form-control" name="eMail" placeholder="E Postanız" /> <br />
        <input type="text" class="form-control" name="location" placeholder="Konumunuz" /> <br />
        <button type="submit" class="btn btn-primary"> Kaydet </button>
    </form>
</div>

<div>
    <a href="#">Veri Listele</a>
</div>

<script src="https://code.jquery.com/jquery-3.7.0.js"></script>

PhoneContacts/Views/Delete/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
 

PhoneContacts/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<h1>Hoşgeldinizzz</h1>


@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

PhoneContacts/Views/Read/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@using EntitiyLayer.Concrete
@model List<User>

<table id="example" class="table table-striped dataTable" style="width: 100%;" aria-describedby="example_info">
    <thead>
        <tr>
            <th>Adı</th>
            <th>Soyadı</th>
            <th>Şirket</th>
            <th>Telefon</th>
            <th>EPosta</th>
            <th>Konum</th>
            <th>#</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.FirstName</td>
                <td>@item.LastName</td>
                <td>@item.Company</td>
                <td>@item.PhoneNumber</td>
                <td>@item.EMail</td>
                <td>@item.Location</td>
                <td><a class="btn btn-info" asp-controller="Delete" asp-action="Index" asp-route-id="@item.UUID">Düzenle</a> <a class="btn btn-danger" href="?Edit=@item.UUID">Düzenle</a> <a href="?Edit=@item.UUID">Düzenle</a></td>
            </tr>
        }
    </tbody>

</table>

PhoneContacts/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PhoneContacts</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/css/bootstrap.min.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/1.13.6/css/dataTables.bootstrap5.min.css" rel="stylesheet" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" >PhoneContacts</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Add"  asp-action="Index">Veri Ekle</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark"  asp-controller="Read" asp-action="Index">Veri Listele</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - PhoneContacts - <a asp-area=""   asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://code.jquery.com/jquery-3.7.0.js"></script>
    <script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.6/js/dataTables.bootstrap5.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>